service: FreePS-dev


frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-plugin-existing-s3
  #- serverless-s3-sync


provider:
  stage: ${opt:stage, 'dev'}
  name: aws
  runtime: python3.6
  region: eu-central-1
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: freeps.${self:provider.stage}
  deploymentBucket:
    name: freeps.${self:provider.stage}


functions:
  ddbMGgetPS:
    name: ${self:provider.stage}_FPS_get_MG
    handler: handler.ddbMGgetPS
    events:
      - http:
          path: /FPS_get_P/FPS_get_MG
          method: get
          cors: true
          integration: lambda

  ddbgetPS:
    name: ${self:provider.stage}_FPS_get_P
    handler: handler.ddbgetPS
    events:
      - http:
          path: /FPS_get_P
          method: get
          cors: true
          integration: lambda

#   createUser_in_table:
#     name: ${self:provider.stage}_createUser_in_table
#     handler: handler.createUser_in_table
#     events:
#       - http:
#           path: /createUser_in_table
#           method: post
#           cors: true
#           integration: lambda
          # authorizer:
          #   arn: arn:aws:cognito-idp:eu-central-1:618057499192:userpool/eu-central-1_3QKfYAo3X







