service: park-serverless


frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-plugin-existing-s3
  - serverless-s3-sync


provider:
  stage: ${opt:stage, 'dev'}     # production or dev
  name: aws
  runtime: python3.6
  region: eu-central-1
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: parknobot.static
        AccessControl: PublicRe
  deploymentBucket:
    name: parknobot.${self:provider.stage}


resources:
  #Resources:
    #AssetsBucket:
      #Type: AWS::S3::Bucket
      #Properties:
        #BucketName: parknobot.static
        #AccessControl: PublicRead
  - ${file(resources/cognito-user-pool.yml)}


custom:
  s3Sync:
    - bucketName: parknobot.static
      localDir: static
      acl: public-read


functions:
  hello:
    name: SERVERLESS_Test_${self:provider.stage}
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true

  admin:
    name: Psevdo-Admin-${self:provider.stage}
    handler: handler.psadmin
    events:
      - http:
          path: /psadmin
          method: get
          cors: true

  groupadd:
    name: Groups-Addind-User-${self:provider.stage}
    handler: handler.groupadd
    events:
      - http:
          path: /groupadd
          method: get
          cors: true




#---------------------------------------Створення---бакета--------------------------------------------------------------



#-----------------------------------------------------------------------------------------------------------------------
