
service: SERVERLESS

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-plugin-existing-s3
  - serverless-s3-sync


provider:
  stage: ${opt:stage, 'dev'}     # production or dev
  name: aws
  runtime: python3.6
  region: us-west-2
  deploymentBucket:
    name: dannobot.${self:provider.stage}


custom:
  s3Sync:
    - bucketName: dannobot.static
      localDir: static
      acl: public-read

functions:
  hello:
    name: SERVERLESS_Test1_${self:provider.stage}
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

          
  imageR:
    name: SERVERLESS_image_${self:provider.stage}
    handler: handler.imageR
    events:
      - http:
          path: /imageR
          method: get






#---------------------------------------Створення---бакета--------------------------------------------------------------

#resources:
#  Resources:
#    AssetsBucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: dannobot.static
#        AccessControl: PublicRead

#-----------------------------------------------------------------------------------------------------------------------

#custom:
#  bucket: testdannobot


#    events:
#      - existingS3:
#        bucket: testdannobot
#        name: vidro
#        rules:
#          - suffix: .png



#deploymentBucket:
#    name:
